name: Missing or wrong aggregation result
description: Report an issue with an aggregation implementation
title: "Missing or wrong aggregation result"
labels: ["bug", "aggregation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue with our aggregation implementation.
        Please provide as much detail as possible to help us reproduce and fix the problem.

  - type: textarea
    id: input
    attributes:
      label: Input
      description: Provide the exact input used for the aggregation
      placeholder: |
        ```typescript
        // Your input code here
        ```
    validations:
      required: true

  - type: textarea
    id: expected-output
    attributes:
      label: Expected Output
      description: Describe or show the output you expected
      placeholder: |
        ```typescript
        // Your expected output here
        ```
    validations:
      required: true

  - type: input
    id: elasticsearch-docs
    attributes:
      label: Elasticsearch Documentation URL
      description: Optional link to relevant Elasticsearch documentation
      placeholder: https://www.elastic.co/guide/en/elasticsearch/reference/current/...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
    validations:
      required: false
