name: Code quality

on:
  push:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .

  typecheck:
    runs-on: ubuntu-latest
    name: typecheck (${{ matrix.elasticsearch-version }}, ${{ matrix.typescript }})
    strategy:
      fail-fast: false
      matrix:
        elasticsearch-version: ["^8", "^9"]
        typescript: [tsgo, typescript]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - name: Remove incompatible tests for v8 (catesian)
        if: matrix.elasticsearch-version == '^8'
        run: |
          rm -f tests/aggregations/metrics/cartesian_bounds.test.ts
          rm -f tests/aggregations/metrics/cartesian_centroid.test.ts
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Install Elasticsearch ${{ matrix.elasticsearch-version }}
        run: bun remove @elastic/elasticsearch && bun add @elastic/elasticsearch@"${{
          matrix.elasticsearch-version }}" --dev

      - name: Run typecheck with tsgo
        if: matrix.typescript == 'tsgo'
        run: |
          bun add @typescript/native-preview@latest --dev
          bunx tsgo --project tsconfig.json --extendedDiagnostics

      - name: Run typecheck
        if: matrix.typescript == 'typescript'
        run: bun run typecheck -- --extendedDiagnostics
